language: cpp

sudo: required
dist: trusty

compiler:
  - gcc

before_install:
  - sudo apt-get update -qq

install:
  - sudo apt-get install -y libssl1.0-dev libcurl4-openssl-dev

before_script:
  - cmake --version

script:
  - ./build.sh -s
  - ./build.sh
  - ./bin/build/tradertests
